[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Open Collaboration Platform"
authors = [{name = "ickby", email = "stefantroeger@gmx.net"}]
dynamic = ["version", "description"]
